### ISSUE TITLE
Bug: Broken ScheduledTasks typescript augmentation

### ISSUE THREAD

**Issue by r-priyam** [sapphiredev/plugins#360] opened 2022-09-24 15:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When augmenting the `ScheduledTasks` interface for multiple tasks, it's only showing the type-hint for one task.

### Steps To Reproduce

1. Clone the repo - https://github.com/r-priyam/scheduled-tasks-ts-error
2. Try creating the tasks using the `container.tasks.create()` or `this.container.tasks.create()`. You will only see one type-hint option for the task name and not two. However, it should show two options as there are two tasks augmentation for it, mainly here -
 - https://github.com/r-priyam/scheduled-tasks-ts-error/blob/main/src/tasks/taskOne.ts
 - https://github.com/r-priyam/scheduled-tasks-ts-error/blob/main/src/tasks/taskTwo.ts

### Expected behavior

It should show `taskOne` and `taskTwo` in the type-hint

### Screenshots

<img width="672" alt="image" src="https://user-images.githubusercontent.com/50884372/192107239-bd88afeb-f4c7-442d-af57-33d8b9d973e0.png">

**Comment by favna** [comment] 2022-09-25 00:43
Closing because we confirmed on Discord that this was related to having multiple `declare module`'s as opposed to one, and therefore also concluded that it's a bug in TS and not this lib.

**Closed by favna** 2022-09-25 00:43 UTC
Labels: bug:confirmed, help wanted, packages:scheduled-tasks
