### ISSUE TITLE
bug: The LoggerPlugin implementation do not allow to replace the logger instance via ClientOptions

### ISSUE THREAD

**Issue by danielpassos** [sapphiredev/plugins#496] opened 2023-11-06 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Since the `LoggerPlugin` is always creating a new instance of logger instance:

```typescript
public static [preGenericsInitialization](this: SapphireClient, options: ClientOptions): void {
	options.logger ??= {};
	options.logger.instance = new Logger(options.logger);
}
```

It's not possible to use the `instance` from `ClientLoggerOptions` to replace the logger on `SapphireClient` 

### Steps To Reproduce

On my SapphireClient:

```typescript
export class MySapphireClient extends SapphireClient {
    public constructor() {
        super({
            logger: {
                instance: new MyLogger()
            },
            ...
        });
    }
}
```

Fire the `container.logger.info('something') and check if that is using the default `Logger` provided by the  [logger plugin](https://github.com/sapphiredev/plugins/tree/main/packages/logger) of the `MyLogger` instance provided on `ClientOptions`

### Expected behavior

`container.logger.*` delegates to `MyLogger` instead of the `Logger` from the [logger plugin](https://github.com/sapphiredev/plugins/tree/main/packages/logger)

**Comment by killbasa** [comment] 2023-11-06 18:51
You can solve this by just not registering the logger plugin. You will still be able to extend it and provide your own instance without issue. I also ran into the same issue a while ago but figured it was intended, maybe just needs to be mentioned in the docs?

**Comment by favna** [comment] 2023-11-06 20:02
Agreed with @killbasa here. Just don't call the `/register`, or don't use the plugin at all. Closing as wont fix.

**Closed by favna** 2023-11-06 20:02 UTC
